### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by nokky-en298** [nokky-en298/protospace-33538#1]
# URL
https://protospace-33538.herokuapp.com/

**Comment by junkiyamada** [comment]
nokky-en298様、ご提出ありがとうございます！
まずは実装お疲れ様でした！

以下2点修正依頼がございますので、ご確認の程何卒よろしくお願いいたします。

・ヘッダーにログインしたユーザー名が表示されている
→不要なので削除してください。

・ログアウト状態だとプロトタイプ一覧が表示されない
→ログインしていてもログアウトしていてもトップページにプロトタイプが表示されるようにしましょう。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
あと一歩です、引き続きがんばりましょう！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by nokky-en298** [comment]
確認ありがとうございます。

上記2点修正致しました。

申し訳ございませんが、再度確認の程よろしくお願い致します。

**Comment by junkiyamada** [comment]
nokky-en298様、再度のご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
